export default {
  biker_attack1:     { end: 5, frameRate: 10, repeat: -1 },
  biker_attack2:     { end: 8, frameRate: 10, repeat: -1 },
  biker_attack3:     { end: 7, frameRate: 10, repeat: -1 },
  biker_climb:       { end: 5, frameRate: 10, repeat: -1 },
  biker_death:       { end: 5, frameRate: 10, repeat:  0-1 },
  biker_djump:       { end: 5, frameRate: 10, repeat:  0-1 },
  // biker_hurt:        { end: 1, frameRate:  5, repeat:  0-1 },
  biker_idle:        { end: 3, frameRate:  5, repeat: -1 },
  biker_jump:        { end: 3, frameRate: 10, repeat:  0-1 },
  biker_kick:        { end: 5, frameRate: 10, repeat:  0-1 },
  biker_run:         { end: 5, frameRate: 10, repeat:  0-1 },
  biker_run_attack:  { end: 5, frameRate: 10, repeat:  0-1 },
  biker_angry:       { end: 5, frameRate: 10, repeat:  0-1 },
  biker_dash:        { end: 5, frameRate: 10, repeat:  0-1 },
  biker_idle2:       { end: 5, frameRate:  5, repeat: -1 },
  biker_hang_fall:   { end: 3, frameRate: 10, repeat:  0-1 },
  biker_hang_idle:   { end: 3, frameRate: 10, repeat:  0-1 },
  biker_happy:       { end: 5, frameRate: 10, repeat:  0-1 },
  // biker_pullup:      { end: 5, frameRate: 10, repeat:  0-1 },
  biker_sit:         { end: 3, frameRate: 10, repeat: -1 },
  biker_talk:        { end: 5, frameRate: 5, repeat: -1 },
  biker_use:         { end: 5, frameRate: 10, repeat:  0-1 },
  biker_walk:        { end: 5, frameRate: 10, repeat: -1 },
  biker_walk_attack: { end: 5, frameRate: 10, repeat:  0-1 },
};
