export default {
  attack1:     { end: 5, frameRate: 10, repeat: -1 },
  attack2:     { end: 8, frameRate: 10, repeat: -1 },
  attack3:     { end: 7, frameRate: 10, repeat: -1 },
  climb:       { end: 5, frameRate: 10, repeat: -1 },
  death:       { end: 5, frameRate: 10, repeat:  0-1 },
  djump:       { end: 5, frameRate: 10, repeat:  0-1 },
  hurt:        { end: 1, frameRate:  5, repeat:  0-1 },
  idle:        { end: 3, frameRate:  5, repeat: -1 },
  jump:        { end: 3, frameRate: 10, repeat:  0-1 },
  kick:        { end: 5, frameRate: 10, repeat:  0-1 },
  run:         { end: 5, frameRate: 10, repeat:  0-1 },
  run_attack:  { end: 5, frameRate: 10, repeat:  0-1 },
  angry:       { end: 5, frameRate: 10, repeat:  0-1 },
  dash:        { end: 5, frameRate: 10, repeat:  0-1 },
  idle2:       { end: 5, frameRate: 10, repeat: -1 },
  hang_fall:   { end: 3, frameRate: 10, repeat:  0-1 },
  hang_idle:   { end: 3, frameRate: 10, repeat:  0-1 },
  happy:       { end: 5, frameRate: 10, repeat:  0-1 },
  pullup:      { end: 5, frameRate: 10, repeat:  0-1 },
  sit:         { end: 3, frameRate: 10, repeat: -1 },
  talk:        { end: 5, frameRate: 10, repeat: -1 },
  use:         { end: 5, frameRate: 10, repeat:  0-1 },
  walk:        { end: 5, frameRate: 10, repeat: -1 },
  walk_attack: { end: 5, frameRate: 10, repeat:  0-1 },
};
