export default {
  biker_unarmed_attack1:     { end: 5, frameRate: 10, repeat: -1 },
  biker_unarmed_attack2:     { end: 7, frameRate: 10, repeat: -1 },
  biker_unarmed_attack3:     { end: 7, frameRate: 10, repeat: -1 },
  biker_unarmed_climb:       { end: 5, frameRate: 10, repeat: -1 },
  biker_unarmed_death:       { end: 5, frameRate: 10, repeat:  0 },
  biker_unarmed_djump:       { end: 5, frameRate: 10, repeat:  0 },
  biker_unarmed_hurt:        { end: 1, frameRate: 10, repeat: -1 },
  biker_unarmed_idle:        { end: 3, frameRate: 10, repeat: -1 },
  biker_unarmed_jump:        { end: 3, frameRate: 10, repeat:  0 },
  biker_unarmed_kick:        { end: 5, frameRate: 10, repeat:  0 },
  biker_unarmed_run:         { end: 5, frameRate: 10, repeat: -1 },
  biker_unarmed_run_attack:  { end: 5, frameRate: 10, repeat:  0 },
  biker_unarmed_angry:       { end: 5, frameRate: 10, repeat:  0 },
  biker_unarmed_dash:        { end: 5, frameRate: 10, repeat:  0 },
  biker_unarmed_idle2:       { end: 5, frameRate: 10, repeat: -1 },
  biker_unarmed_fall:        { end: 3, frameRate: 10, repeat:  0 },
  biker_unarmed_idle_hang:   { end: 3, frameRate: 10, repeat:  0 },
  biker_unarmed_happy:       { end: 5, frameRate: 10, repeat:  0 },
  biker_unarmed_pullup:      { end: 5, frameRate: 10, repeat:  0 },
  biker_unarmed_sit:         { end: 3, frameRate: 10, repeat: -1 },
  biker_unarmed_talk:        { end: 5, frameRate: 10, repeat: -1 },
  biker_unarmed_use:         { end: 5, frameRate: 10, repeat:  0 },
  biker_unarmed_walk:        { end: 5, frameRate: 10, repeat: -1 },
  biker_unarmed_walk_attack: { end: 5, frameRate: 10, repeat:  0 },
};
